import fs from 'fs'
import path from 'path'
import { parseModule, generateCode } from 'magicast'
import { genExport, genInterface, genStringType } from 'knitwork'
import type { ProjectGenerator } from '@doeixd/gen'

function pascal(input: string): string {
  const camel = input
    .replace(/[-_\s]+(.)?/g, (_, c: string) => (c ? c.toUpperCase() : ''))
    .replace(/^(.)/, (m) => m.toUpperCase())
  return camel
}

export default {
  id: 'unjs-demo-generator',
  description: 'Demo generator using Knitwork + Magicast',
  targets: ['frontend'],

  async generate(ctx) {
    const files = ctx.entities.map((entity) => {
      const ifaceName = `${pascal(entity.id)}GeneratedModel`

      const content = [
        '// Generated by unjs-demo-generator',
        genExport(
          genInterface(
            ifaceName,
            Object.fromEntries(Object.keys(entity.fields || {}).map((field) => [field, genStringType()]))
          )
        ),
      ].join('\n\n')

      return {
        path: `src/generated/${entity.id}.generated.ts`,
        content,
      }
    })

    const routesPath = path.join(ctx.rootDir, 'src/routes/index.ts')
    if (fs.existsSync(routesPath)) {
      const source = fs.readFileSync(routesPath, 'utf-8')
      const mod = parseModule(source || 'export {}')

      for (const entity of ctx.entities) {
        ;(mod.exports as Record<string, string>)[`${entity.id}GeneratedRoute`] = `/${entity.name.plural.toLowerCase()}`
      }

      files.push({
        path: 'src/routes/index.ts',
        content: generateCode(mod).code,
        overwrite: true,
      })
    }

    return files
  },
} satisfies ProjectGenerator
